### ISSUE TITLE
react-redux-book-pic

### ISSUE THREAD

**Issue by lewis617** [lewis617/react-redux-tutorial#1]
第五章

1

![image](https://cloud.githubusercontent.com/assets/11524612/15346908/f45e2530-1cee-11e6-94cd-6e12d5ce8bbe.png)

2

![image](https://cloud.githubusercontent.com/assets/11524612/15347006/d4f42cac-1cef-11e6-94bf-37b6ec28ffed.png)

3

![image](https://cloud.githubusercontent.com/assets/11524612/15347179/9963db86-1cf1-11e6-895d-1044898992f9.png)

**Comment by lewis617** [comment]
第六章
![image](https://cloud.githubusercontent.com/assets/11524612/15351134/3b8106b4-1d10-11e6-8dbe-e5a4f45b533d.png)

react 开发者工具

![image](https://cloud.githubusercontent.com/assets/11524612/15967446/5a3c8ae0-2f5a-11e6-824c-002149d65580.png)

![image](https://cloud.githubusercontent.com/assets/11524612/15967503/943e3f72-2f5a-11e6-8569-c330660b2e21.png)

**Comment by lewis617** [comment]
第七章
![image](https://cloud.githubusercontent.com/assets/11524612/15359467/10e2ada0-1d3c-11e6-92de-d263a1b6568c.png)

![image](https://cloud.githubusercontent.com/assets/11524612/15362702/b811a44e-1d48-11e6-90c2-5f0508fe9719.png)

![image](https://cloud.githubusercontent.com/assets/11524612/15363680/10c93720-1d4c-11e6-907d-449454d73f6b.png)

**Comment by lewis617** [comment]
第十章

![image](https://cloud.githubusercontent.com/assets/11524612/15428558/ae4e908e-1ece-11e6-8661-c73eafb8b02d.png)

**Comment by lewis617** [comment]
第十二章

![image](https://cloud.githubusercontent.com/assets/11524612/15447006/9a3cb2ac-1f63-11e6-88e0-310e8ffe0055.png)

**Comment by lewis617** [comment]
第十三章

todomvc

![image](https://cloud.githubusercontent.com/assets/11524612/15983511/6c59adb6-2fdc-11e6-9676-1e4e224f4f17.png)

App组件

![image](https://cloud.githubusercontent.com/assets/11524612/15983646/4a54e10e-2fe1-11e6-8346-da09a798c414.png)

Header组件

![image](https://cloud.githubusercontent.com/assets/11524612/15983657/afd8a236-2fe1-11e6-97b4-f544edcaa98a.png)

TodoTextInput组件
![image](https://cloud.githubusercontent.com/assets/11524612/15983662/0c4bae8c-2fe2-11e6-8770-73358d9b27ce.png)

MainSection组件
![image](https://cloud.githubusercontent.com/assets/11524612/15983676/62c1ab04-2fe2-11e6-8367-c81608441e9d.png)

TodoItem组件
![image](https://cloud.githubusercontent.com/assets/11524612/15983691/da01e94a-2fe2-11e6-8233-5bbc04c717bc.png)

Footer组件

![image](https://cloud.githubusercontent.com/assets/11524612/15983711/72c2a84a-2fe3-11e6-8223-c220d0e9b42e.png)

**Comment by lewis617** [comment]
第15章

程序截屏

![image](https://cloud.githubusercontent.com/assets/11524612/15991116/dd2dedae-30db-11e6-973a-edbfcafe7e8d.png)

log monitor

![image](https://cloud.githubusercontent.com/assets/11524612/15991505/51873ace-30e7-11e6-869e-7afc239b034c.png)

inspector

![image](https://cloud.githubusercontent.com/assets/11524612/15991512/a4a00d4e-30e7-11e6-86e8-68a9ca87e4db.png)

Chart

![image](https://cloud.githubusercontent.com/assets/11524612/15991527/fbed7636-30e7-11e6-90ef-789b8a2febf7.png)

**Comment by lewis617** [comment]
第16章

程序截屏
![image](https://cloud.githubusercontent.com/assets/11524612/15996551/21ca6dc8-315b-11e6-884a-b6b6977f4ffa.png)

![image](https://cloud.githubusercontent.com/assets/11524612/16977163/027e7664-4e87-11e6-987a-904c10e42753.png)

单一状态树结构

![image](https://cloud.githubusercontent.com/assets/11524612/15997426/45e364b6-3166-11e6-8eae-a6a4a8b6b01d.png)

优化

![image](https://cloud.githubusercontent.com/assets/11524612/15998466/23430410-3171-11e6-8b4e-51f6d944ff0b.png)

![image](https://cloud.githubusercontent.com/assets/11524612/15998495/689233ec-3171-11e6-8572-af17cdec3294.png)

![image](https://cloud.githubusercontent.com/assets/11524612/15998561/d507e3d2-3171-11e6-8d78-9a1f227d3987.png)

**Comment by lewis617** [comment]
第17章

程序截图
![image](https://cloud.githubusercontent.com/assets/11524612/16007036/d38f942e-31a2-11e6-9450-800cac4c8bad.png)

 中间件工作流

![image](https://cloud.githubusercontent.com/assets/11524612/16012158/c9d031c4-31ba-11e6-87cf-72d6dabb876d.png)

**Comment by lewis617** [comment]
第18章

程序截屏
![image](https://cloud.githubusercontent.com/assets/11524612/16538659/a362a786-405d-11e6-8b0f-9e93416e60c9.png)

![image](https://cloud.githubusercontent.com/assets/11524612/16538726/544f8b26-405f-11e6-8821-4739e4ccedb9.png)

**Comment by lewis617** [comment]
第19章

![image](https://cloud.githubusercontent.com/assets/11524612/16067215/f011ba1e-32ec-11e6-8765-22614a6c15a6.png)

**Comment by lewis617** [comment]
第20章

![image](https://cloud.githubusercontent.com/assets/11524612/16087540/e47efe82-3355-11e6-94aa-9fb444efcb9e.png)

**Comment by lewis617** [comment]
第21章

![image](https://cloud.githubusercontent.com/assets/11524612/16112694/1a7491ec-33eb-11e6-818c-7656a81eb896.png)

**Comment by lewis617** [comment]
第22章

![image](https://cloud.githubusercontent.com/assets/11524612/16538758/37b4a90a-4060-11e6-9e1c-9ccf0930fb3f.png)

延迟三秒
![image](https://cloud.githubusercontent.com/assets/11524612/16119051/5969c95a-340c-11e6-8bf4-eb8461843f26.png)

开发者工具
![image](https://cloud.githubusercontent.com/assets/11524612/16493658/db08e9d4-3f18-11e6-849a-7a23b52c1cbe.png)

**Comment by lewis617** [comment]
第23章

![image](https://cloud.githubusercontent.com/assets/11524612/16175290/d079cb08-3619-11e6-87e1-f848a9f3d07c.png)

devtools

![image](https://cloud.githubusercontent.com/assets/11524612/16175335/67ac596c-361c-11e6-8c69-b62ea8106d4f.png)

高阶组件

![image](https://cloud.githubusercontent.com/assets/11524612/16175432/ed14a38c-361e-11e6-9c53-589fed1afb5f.png)

展开属性

![image](https://cloud.githubusercontent.com/assets/11524612/16175538/f61b73de-3623-11e6-892e-80078a561b63.png)

**Comment by lewis617** [comment]
第24章

![image](https://cloud.githubusercontent.com/assets/11524612/16177152/bcad3ca2-3657-11e6-910b-daa44b5b08ba.png)

**Comment by houqiangchuan** [comment]
![Uploading QQ图片20160821232013.png…]()
![Uploading QQ图片20160821232007.png…]()
![Uploading QQ图片20160821231948.png…]()
![Uploading QQ图片20160821231940.png…]()
![Uploading QQ图片20160821231924.png…]()
![Uploading QQ图片20160821230721.png…]()

**Comment by houqiangchuan** [comment]
![qq 20160821232020](https://cloud.githubusercontent.com/assets/8922950/17838095/2c19dad4-67f7-11e6-9b30-c6b448869c75.png)
![qq 20160821232013](https://cloud.githubusercontent.com/assets/8922950/17838096/2c4b2184-67f7-11e6-9bb8-c74eff417300.png)
![qq 20160821232007](https://cloud.githubusercontent.com/assets/8922950/17838100/2d519856-67f7-11e6-8060-1e4d04e71db9.png)

![qq 20160821231940](https://cloud.githubusercontent.com/assets/8922950/17838098/2c9a66cc-67f7-11e6-8da9-5bc96ac6f854.png)
![qq 20160821231924](https://cloud.githubusercontent.com/assets/8922950/17838099/2d3c4e06-67f7-11e6-9741-a9935951bb21.png)
![qq 20160821230721](https://cloud.githubusercontent.com/assets/8922950/17838097/2c8e53be-67f7-11e6-95ac-1b3a09c4f45b.png)

**Comment by houqiangchuan** [comment]
![qq 20160821233908](https://cloud.githubusercontent.com/assets/8922950/17838167/8454b57e-67f8-11e6-90c6-ba4f67f9eb87.png)
