### ISSUE TITLE
没有样式文件？？

### ISSUE THREAD

**Issue by EastLee** [lewis617/react-redux-tutorial#14]

**Comment by lewis617** [comment]
todomvc那一章有样式文件，可以参考。如果要在生产环境使用，可以加入css module和post css。可以参考https://github.com/lewis617/react-redux-heroku 。这是我的新书中的例子。

**Comment by lewis617** [comment]
程序截图
![image](https://cloud.githubusercontent.com/assets/11524612/17880446/7c7a382a-692d-11e6-9bc0-02029f30a019.png)
